sudo: required
env:
  matrix:
#ubuntu
  - OS_TYPE=ubuntu OS_VERSION=12.04
  - OS_TYPE=ubuntu OS_VERSION=14.04
  - OS_TYPE=ubuntu OS_VERSION=16.04
#  - OS_TYPE=ubuntu OS_VERSION=18.04
##centos
#  - OS_TYPE=centos OS_VERSION=7.5.1804
#  - OS_TYPE=centos OS_VERSION=7.4.1708
#  - OS_TYPE=centos OS_VERSION=7.3.1611
#  - OS_TYPE=centos OS_VERSION=7.2.1511
#  - OS_TYPE=centos OS_VERSION=7.1.1503
#  - OS_TYPE=centos OS_VERSION=7.0.1406
##opensuse
##  - OS_TYPE=opensuse OS_VERSION=15.0
#  - OS_TYPE=opensuse OS_VERSION=42.3
#  - OS_TYPE=opensuse OS_VERSION=42.2
#  - OS_TYPE=opensuse OS_VERSION=42.1
##debian
#  - OS_TYPE=debian OS_VERSION=wheezy
#  - OS_TYPE=debian OS_VERSION=jessie
#  - OS_TYPE=debian OS_VERSION=stretch
#  - OS_TYPE=debian OS_VERSION=buster
##rhel
#  - OS_TYPE=rhel OS_VERSION=6.10
#  - OS_TYPE=rhel OS_VERSION=7.5
#kali
#windows

services:
  - docker

before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull cloudadminio/${OS_TYPE}:${OS_VERSION}
  - sudo docker run -i -t -d --name linux cloudadminio/${OS_TYPE}:${OS_VERSION} /bin/bash
#try and run this command
script:
#  - TEST=1
  - docker exec -it linux whoami
  - docker exec -it linux bash -c "cd /tmp; bash <(curl -s -L http://bit.ly/cloudadmin-daemon) abcd1234"
  #copy over our unit test into the docker container
  - docker cp unitest-cloudadmin.py linux:/tmp/.
  - ./install_nosetests.sh
#  - docker exec -it linux bash -c "ls /tmp"
#  - docker exec -it linux bash -c "ps auxw"
  - docker exec -it linux bash -c "cat /var/log/glances.log"
  - docker exec -it linux bash -c "TEST=1 glances --quiet --export-http"
  - docker exec -it linux bash -c "nosetests /tmp/unitest-cloudadmin.py"
#  - docker exec -it linux 
#  - docker run cloudadminio/${OS_TYPE}:${OS_VERSION} /bin/bash -c whoami
#  - docker run ${IMAGE} cd /tmp; bash <(curl -s -L http://bit.ly/cloudadmin-daemon) abcd1234; cat /etc/cloudadmin/cloudadmin.conf
#  - docker run cloudadminio/${OS_TYPE}:${OS_VERSION} /bin/bash -c "bash <(curl -s -L http://bit.ly/cloudadmin-daemon) abcd1234"
#  - docker run cloudadminio/${OS_TYPE}:${OS_VERSION} /bin/bash -c "cat /etc/cloudadmin/cloudadmin.conf"
#  - IMAGE=`docker images -q`; docker cp unitest-cloudadmin.py $IMAGE:/tmp/
#  - cat /tmp/unitest-cloudadmin.py
#  - cat /etc/cloudadmin/cloudadmin.conf
