sudo: required
env:
  matrix:
  - OS_TYPE=ubuntu OS_VERSION=12.04
  - OS_TYPE=ubuntu OS_VERSION=14.04
  - OS_TYPE=ubuntu OS_VERSION=16.04
  - OS_TYPE=ubuntu OS_VERSION=18.04

services:
  - docker

before_install:
  - sudo apt-get update
  - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
  - sudo service docker restart
  - sleep 5
  - sudo docker pull cloudadminio/${OS_TYPE}:${OS_VERSION}
  - sudo docker run -i -t -d --name linux cloudadminio/${OS_TYPE}:${OS_VERSION} /bin/bash
#try and run this command
script:
#  - TEST=1
  - docker exec -it linux whoami
  - docker exec -it linux bash -c "cd /tmp; bash <(curl -s -L http://bit.ly/cloudadmin-daemon) abcd1234"
#  - docker exec -it linux 
#  - docker run cloudadminio/${OS_TYPE}:${OS_VERSION} /bin/bash -c whoami
#  - docker run ${IMAGE} cd /tmp; bash <(curl -s -L http://bit.ly/cloudadmin-daemon) abcd1234; cat /etc/cloudadmin/cloudadmin.conf
#  - docker run cloudadminio/${OS_TYPE}:${OS_VERSION} /bin/bash -c "bash <(curl -s -L http://bit.ly/cloudadmin-daemon) abcd1234"
#  - docker run cloudadminio/${OS_TYPE}:${OS_VERSION} /bin/bash -c "cat /etc/cloudadmin/cloudadmin.conf"
#  - IMAGE=`docker images -q`; docker cp unitest-cloudadmin.py $IMAGE:/tmp/
#  - cat /tmp/unitest-cloudadmin.py
#  - cat /etc/cloudadmin/cloudadmin.conf
